baseurl: "/summer"

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


# SEO settings
title: IN Primorsko - Excursions and activities. Hotels&Bars
description: Experience the best of Primorsko with our comprehensive guide to excursions, activities, hotels, restaurants, bars, and more. Nestled along the stunning coastline, Primorsko offers a perfect blend of adventure and relaxation. Explore our curated selection of excursions, from thrilling water sports to scenic hiking trails, and discover the hidden gems of this picturesque destination. Unwind in luxury at our handpicked hotels, indulge in delectable cuisine at our top-rated restaurants, and savor refreshing drinks at our vibrant bars. Whether you're seeking adventure, relaxation, or culinary delights, IN Primorsko is your ultimate guide to an unforgettable experience on the Bulgarian coast.